### ISSUE TITLE
java.nio.ReadOnlyBufferException

### ISSUE THREAD

**Issue by OnlyInAmerica** [Kickflip/kickflip-android-example#4]
Investigate change to FFmpegMuxer to accommodate MediaCodec output buffers becoming read only.

```
AndroidRuntime  E  FATAL EXCEPTION: MicrophoneEncoder
                        E  Process: io.kickflip.sample, PID: 17516
                        E  java.nio.ReadOnlyBufferException
                        E      at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:354)
                        E      at io.kickflip.sdk.av.FFmpegMuxer.addAdtsToByteBuffer(FFmpegMuxer.java:322)
                        E      at io.kickflip.sdk.av.FFmpegMuxer.handleWriteSampleData(FFmpegMuxer.java:217)
                        E      at io.kickflip.sdk.av.FFmpegMuxer.writeSampleData(FFmpegMuxer.java:183)
                        E      at io.kickflip.sdk.av.AndroidEncoder.drainEncoder(AndroidEncoder.java:130)
                        E      at io.kickflip.sdk.av.MicrophoneEncoder.run(MicrophoneEncoder.java:135)
                        E      at java.lang.Thread.run(Thread.java:818)
```

**Comment by OnlyInAmerica** [comment]
Fixed in [8600e9](https://github.com/Kickflip/kickflip-android-sdk/commit/8600e9494ad8352472100d165f767f797a96aadc)
